import "./globals.css";
import Navbar from "./layout/Navbar/Navbar";
import Footer from "./layout/Fotter/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./layout/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ERequirement | ADMIN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full grid gap-1 grid-cols-12`}
      >
        <div className="col-span-2 min-h-full">
          <Sidebar />
        </div>
        <div className="gap-1 col-span-10">
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
